### ISSUE TITLE
Downloading Movies

### ISSUE THREAD

**Issue by fastdragnaught** [NobilityDeviant/ZenDownloader#1]
Unsure if this is an issue or just a problem with the actual site. Ive just tried to download every one piece movie, "fireworks" and "demon slayer recap movie 3" and instead of getting them ive downloaded "5 centimeters per second" every time. download history showing the exact same file size + thumbnails of each file looking idential attached as evidence. 

it does seam to correctly find the movies on the database, also pic below. hoping its just an issue with the site and not the program.

![evidence 3](https://github.com/user-attachments/assets/e8046028-4096-4110-afbe-bdba59255941)
![evidence 2](https://github.com/user-attachments/assets/8d561240-f024-49dc-9167-f52995b2d0d6)
![evidence 4](https://github.com/user-attachments/assets/d9eb74b2-0895-4403-99cf-2fa7bfb31dad)

**Comment by NobilityDeviant** [comment]
Thank you for reporting this. Not to get too technical, but there's a category tag for movies and apparently there's more than one. I use the default: 46540 but some have different ones.

It uses [wcostrean](https://www.wcostream.tv/movie-list#O) for the movies

Click on a movie, click on Watch On Playlist and you've bypassed the paywall.

I will work on this in a bit

**Comment by NobilityDeviant** [comment]
This issue has been fixed in the new release: [1.0.1](https://github.com/NobilityDeviant/ZenDownloader/releases/tag/1.0.1)

**Comment by fastdragnaught** [comment]
can confirm this has been fixed !
