### ISSUE TITLE
Download list doesn't expand to window size

### ISSUE THREAD

**Issue by hungLink** [NobilityDeviant/ZenDownloader#10]
![image](https://github.com/user-attachments/assets/323598f6-1d85-4892-ae16-5ce607216a76)

**Comment by NobilityDeviant** [comment]
Yes the episodes are capped at a certain height because I was having issues with it going off screen due to the row of buttons on the bottom bar. It also can't have infinity height since it's a lazycolumn and it throws an error if you do, I'm not entirely sure how to fix this, but I'll look around.

**Comment by NobilityDeviant** [comment]
Fixed in [Commit](https://github.com/NobilityDeviant/ZenDownloader/commit/c06f240ef93c6ed6b698081d9ded190493df5ac1)
