### ISSUE TITLE
Feature Request: Alphabetize Download List

### ISSUE THREAD

**Issue by hungLink** [NobilityDeviant/ZenDownloader#11]
A screenshot doesn't really get the point across so, I thought it might be nice to take a video
https://www.youtube.com/watch?v=Asf9PamOk1w

**Comment by hungLink** [comment]
It may also be nice to throw a version style sorting in there so that 101 comes before 1000.

**Comment by NobilityDeviant** [comment]
Btw I think the one piece download list is special. Maybe theres other animes, but I've never seen anything else with 1k+ episodes.

The suggestions are great overall and something I have thought of, but if you can find me some scrapable list of one piece data I'd appreciate it.

Like a list of all the episode names sorted by their seasons so I can manually update it.

**Comment by hungLink** [comment]
Ooh! I could do that!

That's a great idea!

**Comment by hungLink** [comment]
Wikipedia has a list of all the seasons and episodes.

I plan to scrape this info, and rename all my files accordingly as well.
