### ISSUE TITLE
Download queue gets stuck after 3 episodes downloaded

### ISSUE THREAD

**Issue by PhantomSlash64** [NobilityDeviant/ZenDownloader#14]
There is an Issue I run into that happens everytime is when you queue to download an entire series, After 3 episodes are downloaded the downloads hang and never download. It would be nice if there was a fix for this issue.

**Comment by NobilityDeviant** [comment]
I'm going to need some more details regarding this issue.

1: The link/name of series you are trying to download

2: Any logs you see after enabling debug messages in the settings

**Comment by PhantomSlash64** [comment]
1. Bunnicula https://www.wcoforever.net/anime/bunnicula
2. Where do I my log file path to submit to?
Thanks. Forgive me because this is the first time I'm doing this type of stuff.

**Comment by NobilityDeviant** [comment]
That's ok the series link is more than enough.
The program doesn't currently support episodes with 2 videos, but I'm working on an update and i'll see what I can do about this.
Specifically: https://www.wcofun.net/bunnicula-episode-1-2-mumkey-business-walking-fish this one right here. 
and possibly others. I did notice how it hangs and stops downloading entirely.
I'll look into this.

**Comment by PhantomSlash64** [comment]
Thank you! You are a godsend against corporations making viewing shows harder and harder! 😎✌️

**Comment by NobilityDeviant** [comment]
This has been fixed in [1.0.5](https://github.com/NobilityDeviant/ZenDownloader/releases/tag/1.0.5)

Please let me know if you still have any issues in the next week. If you don't respond, I'll close this issue.

**Comment by NobilityDeviant** [comment]
Assuming this is fixed i'm closing the issue
