### ISSUE TITLE
Issuies downloading frieren beyond journeys end

### ISSUE THREAD

**Issue by fastdragnaught** [NobilityDeviant/ZenDownloader#16]
Hey man, ive noticed that some animie is using a differnt video player, which you have to select which launguage you want. Also unlike what normally on the site you cant right click on the video and download it that way either.

Zen Downloader is able to find the episodes and attempt a download, but will either get stuck trying to download it while showing that the episode had 0mb or will instantly fail showing that.
![frieren](https://github.com/user-attachments/assets/aaa287d3-50b1-459a-ae9a-3e2fdc7759ff)

After another attempt to download the first episode I was able to get the video but no audio.

**Comment by NobilityDeviant** [comment]
Also note that you won't have to choose any language on the video manually. The program just doesn't support this right now. The m3u8 comes packed with something like so:

```
#EXTM3U
#EXT-X-STREAM-INF:BANDWIDTH=12000000,CODECS="avc1.64002a",RESOLUTION=1920x1080,AUDIO="audio",SUBTITLES="subs"
0/1920/index.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1000000,CODECS="avc1.64002a",RESOLUTION=1280x720,AUDIO="audio",SUBTITLES="subs"
0/1280/index.m3u8
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio",LANGUAGE="eng",NAME="eng_1",URI="1/eng/index.m3u8"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio",LANGUAGE="spa",NAME="spa_2",URI="2/spa/index.m3u8"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio",LANGUAGE="spa",NAME="spa_3",URI="3/spa/index.m3u8"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio",LANGUAGE="fre",NAME="fre_4",URI="4/fre/index.m3u8"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio",LANGUAGE="ger",NAME="ger_5",URI="5/ger/index.m3u8"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio",LANGUAGE="ita",NAME="ita_6",URI="6/ita/index.m3u8"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio",LANGUAGE="por",NAME="por_7",URI="7/por/index.m3u8"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio",LANGUAGE="pol",NAME="pol_8",URI="8/pol/index.m3u8"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio",LANGUAGE="tur",NAME="tur_9",URI="9/tur/index.m3u8"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio",LANGUAGE="jpn",NAME="jpn_10",URI="10/jpn/index.m3u8"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio",LANGUAGE="jpn",NAME="jpn_11",URI="11/jpn/index.m3u8"
#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="subs",LANGUAGE="eng_12",NAME="eng_12",AUTOSELECT=YES,DEFAULT=NO,URI="subtitle/12_eng_vtt.m3u8"
#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="subs",LANGUAGE="eng_13",NAME="eng_13",AUTOSELECT=YES,DEFAULT=NO,URI="subtitle/13_eng_vtt.m3u8"
#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="subs",LANGUAGE="spa_14",NAME="spa_14",AUTOSELECT=YES,DEFAULT=NO,URI="subtitle/14_spa_vtt.m3u8"
#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="subs",LANGUAGE="spa_15",NAME="spa_15",AUTOSELECT=YES,DEFAULT=NO,URI="subtitle/15_spa_vtt.m3u8"
#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="subs",LANGUAGE="spa_16",NAME="spa_16",AUTOSELECT=YES,DEFAULT=NO,URI="subtitle/16_spa_vtt.m3u8"
```

I will have to add extra options and check to select your own language for audios. I'm not sure about subtitles, but I'll see what I can do.

Thank you i'll keep you all updated

**Comment by fastdragnaught** [comment]
thanks man thats brilliant stuff ! Just Tired to download frieren beyond journeys end and it almost went smoothly ! all of them downloaded except episode 20, tho im guessing this might just be an issue with the site.

When I look at the download queue its showing that the audio file is downloading but the video isnt. Ive tried deleting all files / folders relating to this episode and then trying again, but i keep running into the same issue. Ive checked the site and the video does play.....

seams to download on 720p but not 1080p

**Comment by NobilityDeviant** [comment]
> thanks man thats brilliant stuff ! Just Tired to download frieren beyond journeys end and it almost went smoothly ! all of them downloaded except episode 20, tho im guessing this might just be an issue with the site.
> 
> When I look at the download queue its showing that the audio file is downloading but the video isnt. Ive tried deleting all files / folders relating to this episode and then trying again, but i keep running into the same issue. Ive checked the site and the video does play.....
> 
> seams to download on 720p but not 1080p

Sometimes there's no video for certain resolutions even if it's detected. I completely forgot to add a backup option for m3u8 too. I will look into that since it's a bit more complicated than regular videos.
