### ISSUE TITLE
No audio on downloads

### ISSUE THREAD

**Issue by Max1Mil** [NobilityDeviant/ZenDownloader#17]
When downloading anime and trying to play after download complete the video has no audio. It has the whole episode but no audio for the entire thing. Maybe I am doing something wrong. If so i do apologize.

this was for jujutsu kaisen episode 22 and 23. I did notice on the site you have to choose a language for these episodes. I tried picking the language and then also trying to download with the episode url instead of the season url but had same result.

![Screenshot 2024-11-05 192854](https://github.com/user-attachments/assets/d8bee587-155f-4a75-87c4-3aadae9a8ce6)

**Comment by NobilityDeviant** [comment]
Keep track on issue #16 
I'll work on this soon.
