### ISSUE TITLE
ZenDownloader Working (Sort-of On Windows 7)

### ISSUE THREAD

**Issue by leomarvin736** [NobilityDeviant/ZenDownloader#2]
Hello,

I have come across this issue when running ZenDownloader on Windows 7
![ZenDownloader On Windows 7](https://github.com/user-attachments/assets/d7c191c8-d607-45d5-ab49-e4f2a6331949)
It seems to be working, but all the clickable buttons and settings have no text.

I'm not sure if you intended your downloader to work on older operating systems other then Windows 10 and above, but it seems like it could work.

Also, the _Asset Updater_  does not run as well when launched.

**Comment by NobilityDeviant** [comment]
Ok thank you for reporting.  That's very strange and I wouldn't know whats the issue without running windows 7 myself and debugging. I will try to run windows 7 in some virtual machine and see how it goes.
It's low priority, but there's not much issues right now, so I will get to it soon.

**Comment by NobilityDeviant** [comment]
Also since the asset downloader isn't updating, I've added an extra bit of info for you in the database readme: [Database][(url](https://github.com/NobilityDeviant/ZenDownloader/blob/master/database/README.md#database))

that i left out under the **Wco Data** part

**Comment by NobilityDeviant** [comment]
Ok I have just tested this and it's working fine for me.

<img width="590" alt="Screenshot_1" src="https://github.com/user-attachments/assets/273f7916-39f7-4782-ac22-da93dd3dfb96">

With some fallback, but it functions normally.

One thing I did have to do though was install this: [https://www.microsoft.com/en-us/download/details.aspx?id=48145](https://www.microsoft.com/en-us/download/details.aspx?id=48145)

**Comment by NobilityDeviant** [comment]
Sorry for the spam. I just need to keep track of my findings.

I figured out the other windows don't show because they're undecorated.

Now it's time to figure out how to detect windows 7 and adjust accordingly.

**Comment by NobilityDeviant** [comment]
Ok I fixed the windows issue and a chrome issue in: [1.0.2](https://github.com/NobilityDeviant/ZenDownloader/releases/tag/1.0.2)

but I wasn't able to replicate the missing texts. It just seems to be a compose issue I'll have to report.

**Comment by leomarvin736** [comment]
Thanks, I'll let you know how it goes.

**Comment by leomarvin736** [comment]
So, to date since update 1.0.2

On my end, I uninstalled my prerequisites and installed the prerequisite you posted above: https://www.microsoft.com/en-us/download/details.aspx?id=48145

I even tested with never versions as well of the prerequisite.

I did a reboot after I installed the prerequisite and then proceeded to install ZenDownloader 1.0.2

On my end, upon first run I am able to see the _Asset Updater_ window.
![Assest Updater](https://github.com/user-attachments/assets/4580e64a-8c71-401c-8b30-17c12df471ac)
But like before, the text is still not showing up
![ZenDownloader Windows 7](https://github.com/user-attachments/assets/e99aab1c-120e-446b-bfe7-ba33dba4a40c)
I also tried to change my Windows Theme from Areo, to Basic, to Classic.

I thought maybe it had something to do with the theme, but it made no difference.

**Comment by NobilityDeviant** [comment]
What version of windows 7 do you have?

I used this: [https://archive.org/details/en_windows_7_ultimate_with_sp1_x64_dvd_u_677332_202006](https://archive.org/details/en_windows_7_ultimate_with_sp1_x64_dvd_u_677332_202006)

Do you mind if i pass you a debug version to use?
It will show errors inside a console or spit them out to a text file.

**Comment by leomarvin736** [comment]
I'm running Windows 7 Professional 64-bit Service Pack 1.

It's activated and all service updates, security update and stability updates have been installed.

You can send me a debug version if you want.

**Comment by NobilityDeviant** [comment]
Ok so it's either a difference between the versions or maybe the graphics card?

try this: [https://www.dropbox.com/scl/fi/hwbfujllxbodz2beubzjo/ZenDownloader-1.0.2-console.exe?rlkey=devi3vigvb9usivghwzb93ehl&st=gc22ksgk&dl=1](https://www.dropbox.com/scl/fi/hwbfujllxbodz2beubzjo/ZenDownloader-1.0.2-console.exe?rlkey=devi3vigvb9usivghwzb93ehl&st=gc22ksgk&dl=1)

and let me know what the console says.
you'll have to uninstall the current zendownload because it's the same version

**Comment by leomarvin736** [comment]
Okay, will do. 👍

**Comment by leomarvin736** [comment]
My graphics card driver was the issue.

I had to update it to the latest driver version on the manufacturers website.

My graphics card driver came from Windows Update so I guess it was missing something

Overall everything is working with very minor hiccups.

![ZenDownloader Working](https://github.com/user-attachments/assets/56f421cf-4591-43fe-9d81-44f22c84fd12)


The only thing I'm getting in the console upon startup is this:
_[1:45] [SKIKO] warn: Fallback to next API
[1:45] org.jetbrains.skiko.RenderException: Failed to choose DirectX12 adapter._

But it's not stopping me from downloading stuff from wcofun.

So the problem was on my end, and no fault of your downloader.

I'm pretty sure that if I was to download your initial release, it would work now.

You can look in to that error I mentioned above if you want to, but the downloader is working even with that error.

Thanks for all your help and time and if there are more problems, I'll open a new issue.

As for this problem, it has been solved.
