### ISSUE TITLE
1.0.1 update

### ISSUE THREAD

**Issue by fastdragnaught** [NobilityDeviant/ZenDownloader#3]
tried to update to the latest version, i uninstalled / deleted any files relating to the previous version. upon doing a fresh install the program would fail to update all assets, after closing down that page the program would load but I would be unable to download anything. Ive got screenshots of this + the error console. 

Noticed the error console talked about "movies.txt (access denied) and what had downloaded in my files wasnt a .txt file but a folder (screenshot provided) after downloading the correct "movies.txt" and deleting the folder the program loaded.

![evidence 1](https://github.com/user-attachments/assets/0ccf7fb5-f44e-42c2-8c55-844a2b726343)
![evidence 2](https://github.com/user-attachments/assets/c849d351-12eb-48c1-85d7-5098769df441)
![evidence 3](https://github.com/user-attachments/assets/cc9ec5fc-4393-4422-9e13-c6e50ef181b5)

**Comment by NobilityDeviant** [comment]
Ah my mistake ok thank you for reporting.
I was in a rush and didn't really test that.
I will fix this alongside the other issues in a bit

**Comment by NobilityDeviant** [comment]
This issue has fixed in: [1.0.2](https://github.com/NobilityDeviant/ZenDownloader/releases/tag/1.0.2)
