### ISSUE TITLE
Comparison method violates its general contract: repro fuzzy

### ISSUE THREAD

**Issue by hungLink** [NobilityDeviant/ZenDownloader#6]
This program fails if you install it somewhere other than the default filepath.
It gives errors like
`Failed to launch JVM` and `Comparison method violates its general contract`

Workaround:
Don't change the install location in the wizard

**Comment by hungLink** [comment]
This is happening to me now even with the default path. 
The last thing I did was stop a download, and immediately hit the start button to select different episodes.

Uninstall and reinstall does not work.
Changing the path to one that has never been used by the application didn't fix it either.

I'm going to restart my machine and see if that helps.

**Comment by hungLink** [comment]
Restart didn't fix it.

**Comment by hungLink** [comment]
Killing the task in task manager and deleting the zendatabase in my user dir fixed it.

**Comment by NobilityDeviant** [comment]
Ah i wanted to see the error but you did figure it out. Yes it's not an install issue, it's an issue with the sorting for the lists. Clearing the user folder resulted in no downloads to be sorted so the error is gone. 

What did you download to make this happen? Anything specific?

**Comment by hungLink** [comment]
https://www.wcofun.net/anime/one-piece-english-subbed

**Comment by NobilityDeviant** [comment]
Issue should be fixed since I changed the comparators awhile ago.
