### ISSUE TITLE
Feature request: Select multiple episodes for download using the shift key

### ISSUE THREAD

**Issue by hungLink** [NobilityDeviant/ZenDownloader#7]
It would be nice if you could click on an episode in the download list, and then use shift to click on one lower in the list, and check them all.

Like if you click episode 3, hold shift, and click episode 17, episodes 3-17 should be selected for download.

Workaround:
Click each episode you want one at a time

**Comment by NobilityDeviant** [comment]
That's a good idea. I could do that for the next update

**Comment by NobilityDeviant** [comment]
Added in [Commit](https://github.com/NobilityDeviant/ZenDownloader/commit/c06f240ef93c6ed6b698081d9ded190493df5ac1)

Will push an update when everything is added. I just want to clear some issues
